Memo db
rosh-1228/memo pull request #3
Opened 2021-12-02 00:17 UTC by rosh-1228

DBとの接続、SQLインジェクション対策、テストコードの修正をしました！

2021-12-07 03:05 UTC, u1tnk requested changes

2021-12-07 03:05 UTC, u1tnk commented on helpers/helpers.rb
> +    PG.connect(dbname: 'memos')
> データベースに接続するのは重い処理です。1リクエストで何度も接続しないように工夫しましょう。

が対応されていないので、対応お願いします。

2021-12-07 03:05 UTC, u1tnk commented on helpers/crud_helpers.rb
> +      connect_db.exec_params("#{query} WHERE id = $1", [params['id']]).each do |values|
idで検索すれば結果は必ず一つになると思います。
eachだとたくさんありそうに見えるので `first`とかで一件だけ取った方が良いですね。

2021-12-07 03:05 UTC, u1tnk commented on app.rb
> +    @context = params['text']
textがcotextになってますが、システム開発でcontextという単語は 背景とか文脈とかの意味でよく使われるので適当では無いです。
textの方が比較的良さそうですが、なぜ変更したのでしょうか？
ちなみにこういうときによく使われる他の単語としては `body`とか `content`とかをよく見ます。

2021-12-09 01:20 UTC, rosh-1228 commented on helpers/helpers.rb
> +    PG.connect(dbname: 'memos')
ご指摘ありがとうございます💦
connectionpoolを使用して、負荷を軽減するようにしました。

2021-12-09 01:21 UTC, rosh-1228 commented on app.rb
> +    @context = params['text']
contextをcontentと勘違いして使っていました💦
contextとしているところをtextと変更しました。

2021-12-09 01:21 UTC, rosh-1228 commented on helpers/crud_helpers.rb
> +      connect_db.exec_params("#{query} WHERE id = $1", [params['id']]).each do |values|
firstで1件だけ取得するように変更しました！

2021-12-09 02:59 UTC, u1tnk approved these changes

2021-12-09 02:59 UTC, u1tnk commented on helpers/helpers.rb
> +    PG::EM::ConnectionPool.new(size: 1, dbname: 'memos')
connection_pool gemを入れたわけですね。
connectionオブジェクトをインスタンス変数に保存する…ぐらいの処理を想定してましたが、もちろん問題無いです 🙆‍♀️

2021-12-09 03:23 UTC, rosh-1228 commented on helpers/helpers.rb
> +    PG::EM::ConnectionPool.new(size: 1, dbname: 'memos')
ありがとうございます！
インスタンス変数に保存した方が良いのですね😓

2021-12-09 03:24 UTC, merged